kind: pipeline
type: docker
name: gecko

steps:
- name: build-ava
  image: golang:1.13.9-buster
  when:
    branch: master
    event: push
  commands:
  - apt-get -y install cmake libssl-dev libuv1-dev g++
  - scripts/build.sh

