kind: pipeline
type: docker
name: gecko

steps:
- name: build-ava
  image: golang:1.13.9-buster
  when:
    branch: master
    event: push
  commands:
  - apt-get -y update
  - apt-get -y install cmake libssl-dev libuv1-dev
  - scripts/build.sh

#- name: test
#  image: alpine
#  commands:
#  - echo hellow
#  - pwd
#  - ls -la build


- name: fedora-31
  image: fedora:31
  volumes:
  - name: hostdir
    path: /tmp/hostdir
  commands:
  - deploy/rpm/build.sh

#- name: ubuntu-18.04
#  image: ubuntu:bionic
#  commands:
#    - deploy/deb/build.sh

volumes:
- name: hostdir
  host:
    path: /tmp/build