kind: pipeline
type: docker
name: gecko

volumes:
  - name: store
    temp: {}

steps:
- name: build-ava
  image: golang:1.13.9-buster
  when:
    branch: master
    event: push
  commands:
  - apt-get -y update
  - apt-get -y install cmake libssl-dev libuv1-dev
  - scripts/build.sh


- name: fedora-31
  image: fedora:31
  group: package
  volumes:
  - name: store
    path: /store
  environment:
    GIT_TAG: "${DRONE_TAG}"
    GIT_COMMIT: "${DRONE_COMMIT_SHA:0:8}"
  commands:
  - deploy/rpm/build.sh


#- name: scp files
#  image: appleboy/drone-scp
#  volumes:
#    - name: cache
#      path: /cache
#  settings:
#    host: 50.116.4.66
#    username: root
#    password:
#      from_secret: ssh_password
#    port: 22
#    target: /tmp/build/
#    source: /cache/*.rpm

- name: ubuntu-18.04
  image: ubuntu:bionic
  group: package
  volumes:
  - name: store
    path: /store
  environment:
    GIT_TAG: "${DRONE_TAG}"
    GIT_COMMIT: "${DRONE_COMMIT_SHA:0:8}"
  commands:
    - apt-get -y update
    - deploy/deb/build.sh


- name: test
  image: alpine
  volumes:
    - name: store
      path: /store
  commands:
    - ls -la /store/

