kind: pipeline
type: docker
name: gecko

steps:
- name: build-ava
  image: golang:1.13.9-buster
  when:
    branch: master
    event: push
  commands:
  - apt-get -y update
  - apt-get -y install cmake libssl-dev libuv1-dev
  - scripts/build.sh

#- name: test
#  image: alpine
#  commands:
#  - echo hellow
#  - pwd
#  - ls -la build


#- name: fedora-31
#  image: fedora:31
#  volumes:
#  - name: hostdir
#    path: /tmp/hostdir
#  volumes:
#  - name: cache
#    path: /cache
#  commands:
#  - deploy/rpm/build.sh
#  - cp /tmp/rpm/RPMS/x86_64/*.rpm /cache/

#- name: scp files
#  image: appleboy/drone-scp
#  volumes:
#    - name: cache
#      path: /cache
#  settings:
#    host: 50.116.4.66
#    username: root
#    password:
#      from_secret: ssh_password
#    port: 22
#    target: /tmp/build/
#    source: /cache/*.rpm

- name: ubuntu-18.04
  image: ubuntu:bionic
  commands:
    - apt-get -y update
    - deploy/deb/build.sh

#volumes:
#- name: hostdir
#  host:
#    path: /tmp/build

volumes:
- name: cache
  temp: {}