#!/usr/bin/expect
#
# script is used by the publish.sh script for signing the RPM's.
#
# it uses "expect" to pass the passphrase of the GPG key set during the CI
# runtime through a templated variable %%passphrase%%

set timeout -1
spawn sh -c "rpm --resign *.rpm"
match_max 100000
expect -exact "Enter pass phrase: "
send -- "%%PASSPHRASE%%\r"
expect eof
